- hosts: localhost
  name: New System Setup
  gather_facts: true

  vars:
    home: "{{ lookup('env', 'HOME') }}"
    user: "{{ lookup('env', 'USER') }}"
    node_version: "16"

  pre_tasks:
    - name: Update Package Manager - Debian - Apt
      become: true
      ansible.builtin.apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
        - core
      when: ansible_os_family == "Debian"

  tasks:
    - name: setup docker
      import_tasks: tasks/docker.yml
    - name: setup docker
      import_tasks: tasks/setup.yml
